graph LR
1[(startevent)] --> 2(GO requests measurements)
2 --> 3(MSP checks request)
3 --> 4{x}
4 --> 5[MSP denies request]
4 --> 6(MSP performs measurement)
6 --> 7(MSP informs GO of failure)
7 --> 8[(endevent)]
6 --> 9(MSP transmits measured values)
9 --> 10(GO processes measured values)
10 --> 11(GO sends changed values)
11 --> 12(GO transmits readings to SP)
12 --> 8[(endevent)]