graph LR
1:startevent:((startevent)) --> 2:task:(Sales Department Receive Order)
2 --> 3:exclusivegateway:{x}
3 --> 4:task:(Reject Order):|no|
3 --> 5:task:(Accept Order):|yes|
5 --> 6:task:(Inform Storehouse and Engineering Department)
6 --> 7:task:(Storehouse Process Part List)
7 --> 8:task:(Check Required Quantity)
8 --> 9:task:(Reserve Part):|available|
8 --> 10:task:(Back-Order Part):|not available|
9 --> 11:task:(Prepare for Assembling)
10 --> 11
11 --> 12:task:(Assemble Bicycle)
12 --> 13:task:(Ship Bicycle to Customer)
13 --> 14:endevent:((endevent))