graph LR
A[Start Event] --> B[GO requests measurements to MSP]
B --> C[MSP checks request]
C -->|Denied| D[MSP informs GO about failure]
C -->|Performed| E[MSP performs measurement]
E --> F[MSP transmits measured values to GO]
F --> G[GO processes measured values]
G --> H[GO sends changed values to MSP]
H --> I[GO transmits readings to SP]
I --> J[End Event]
