graph LR
A[Start Event] --> B[Sales Department]
B --> C[Reject/Accept Order]
C -->|Reject| D[End Event]
C -->|Accept| E[Storehouse]
E --> F[Check Part List]
F --> G[Reserve/Back-Order]
G --> H[Engineering Department]
H --> I[Prepare for Assembling]
I --> J[Assemble Bicycle]
J --> K[Sales Department]
K --> L[Ship Bicycle]
L --> M[End Event]
